txt=open('cwnd.txt').readlines()
w=open('cwmd_handle.txt','w') 
for line in txt:
    line=line.replace(' 	 reno wscale:','')
    line=line.replace('9 rto:','')
    line=line.replace(' rtt:',',')
    line=line.replace('/',',')
    line=line.replace(' mss:',',')
    line=line.replace(' cwnd:',',')
    line=line.replace(' ssthresh:',',')
    line=line.replace(' bytes_acked:',',')
    line=line.replace(' segs_out:',',')
    line=line.replace(' segs_in:',',')
    line=line.replace(' send ',',')
    line=line.replace('Mbps','')
    line=line.replace(' lastsnd:',',')
    line=line.replace(' lastrcv:',',')
    line=line.replace(' lastack:',',')
    line=line.replace(' pacing_rate ',',')
    line=line.replace('Mbps','')
    line=line.replace(' unacked:',',')
    line=line.replace(' retrans:',',')
    line=line.replace('/',',')
    line=line.replace(' reordering:',',')
    line=line.replace(' lost:',',')
    line=line.replace(' sacked:',',')
    line=line.replace(' rcv_space:',',')
    w.write(line)